### PR TITLE
Create platform-revolution-notes.md

### PR DESCRIPTION
**Pull request by venetucci**
I started adding a scaffold of notes for Platform Revolution. I'm starting with chapters 7 & 8. 

✨📖✨

TODO:
- [x] Add basic outline for chapter 7: Openness
- [x] Add basic outline for chapter 8: Governance
- [x] Fill in basic points more extensively
- [x] Add case studies to appropriate sections
- [x] Review/get changes from @jtescher & @pifafu

### CODE REVIEW

**Review by jtescher — CHANGES_REQUESTED** [review]
Maybe add a section for case studies?

- Facebook vs Myspace
- Apple vs Microsoft
- iOS vs Android
- Betamax vs VHS
- HD-DVD vs Bluray

**Comment by pifafu** [comment]
I'll be adding some notes today, tomorrow, Friday! 🙏 Thanks for setting this uppppppp ✨ 😻

**Comment by venetucci** [comment]
@pifafu !! YAY! I just saw this, so I was adding more notes today - I'm running out of steam, feel like filling in more of Chapter 8?

I also feel like I'm probably recording too much / not summarizing concisely enough, if you can find any places to streamline the notes... 🙏

**Comment by pifafu** [comment]
Sure :) Aren't you on vacation??! 🤔 I will do some suggestions if I find opportunities to condense or streamline.

**Pull request merged**
